Repository fadhilyori/subping, pull requests merged in 2023-07, with the labels that each got.

#1 Add network package
  cmd/subping/main.go
  pkg/network/network.go
  pkg/network/network_test.go
Labels: enhancement

#4 update readme
  README.md
  docs/README.md
  docs/network/README.md
Labels: documentation

#7 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#8 fix invalid memory address or nil pointer dereference error
  subping.go
Labels: bug

#11 Improve help usage, add versioning and makefile script
  .gitignore
  Makefile
  cmd/subping/main.go
  go.mod
  go.sum
Labels: enhancement

#10 fix: first IP of CIDR range
  pkg/network/network.go
Labels: enhancement, question

#17 Update pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#16 Add new flags, improve unit test and bug fixing
  README.md
  assets/images/usage-example.png
  cmd/subping/main.go
  docs/README.md
  docs/network/README.md
  pkg/network/network.go
  pkg/network/network_test.go
  subping.go
  subping_test.go
Labels: enhancement

#13 Fix Sorting Algorithm Bug
  cmd/subping/main.go
Labels: bug, good first issue

#24 23 memory leak issue in the network package when handling a large range of ipv6 hosts
  README.md
  assets/images/usage-example.png
  cmd/subping/main.go
  docs/README.md
  docs/network/README.md
  go.mod
  go.sum
  pkg/network/network.go
  pkg/network/network_test.go
  subping.go
  subping_test.go
Labels: bug, enhancement

#27 replace deprecated go-ping with pro-bing
  README.md
  go.mod
  go.sum
  subping.go
Labels: enhancement

#28 fix: table print formatting when printing IPv6 addresses
  cmd/subping/main.go
Labels: bug

#30 docs: update README.md
  README.md
Labels: documentation

#32 feat: Add Dockerfile and GitHub workflow for automated image builds
  .dockerignore
  .github/workflows/deploy-image.yml
  Dockerfile
  Makefile
Labels: enhancement
